USE test
GO

CREATE TABLE LIBRARY_BOOKS 
(
	ISBN CHAR(14),
	BOOK_TITLE VARCHAR(50),
	CONSTRAINT BOOKS_ISBN_PK PRIMARY KEY (ISBN)
);

INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-0670033041','East of Eden');
INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-1250303882','Five Ingredients');
INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-0062390622','The Alchemist');
INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-1787016965','The Travel Atlas');
INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-0141392462','The Count of Monte Cristo');
INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-0618640157','The Lord of the Rings');
INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-0446568814','Rich Dad Poor Dad');
INSERT INTO LIBRARY_BOOKS (ISBN, BOOK_TITLE) VALUES ('978-0060752613','The Intelligent Investor');


CREATE TABLE LIBRARY_CUSTOMERS
(
	PERSON_ID INT,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	CONSTRAINT LIBRARY_CUSTOMERS_PERSON_ID_PK PRIMARY KEY (PERSON_ID)
);

INSERT INTO LIBRARY_CUSTOMERS (PERSON_ID, FIRST_NAME, LAST_NAME) VALUES (101,'Judy','Jackson');
INSERT INTO LIBRARY_CUSTOMERS (PERSON_ID, FIRST_NAME, LAST_NAME) VALUES (102,'William','Davis');
INSERT INTO LIBRARY_CUSTOMERS (PERSON_ID, FIRST_NAME, LAST_NAME) VALUES (103,'Sarah','Romano');
INSERT INTO LIBRARY_CUSTOMERS (PERSON_ID, FIRST_NAME, LAST_NAME) VALUES (104,'Jerry','Kumar');
INSERT INTO LIBRARY_CUSTOMERS (PERSON_ID, FIRST_NAME, LAST_NAME) VALUES (105,'Craig','Todd');


CREATE TABLE BOOK_CHECKOUTS_REPORT
(
	PERSON_ID INT,
	BOOK_TITLE1 VARCHAR(50),
	BOOK1_DUE_DATE DATE,
	BOOK_TITLE2 VARCHAR(50),
	BOOK2_DUE_DATE DATE
);

INSERT INTO BOOK_CHECKOUTS_REPORT (PERSON_ID, BOOK_TITLE1, BOOK1_DUE_DATE, BOOK_TITLE2, BOOK2_DUE_DATE) VALUES (101, 'East of Eden','2020-07-20','Five Ingredients','2020-07-20');
INSERT INTO BOOK_CHECKOUTS_REPORT (PERSON_ID, BOOK_TITLE1, BOOK1_DUE_DATE, BOOK_TITLE2, BOOK2_DUE_DATE) VALUES (101, 'The Alchemist','2020-07-20','The Travel Atlas','2020-07-20');
INSERT INTO BOOK_CHECKOUTS_REPORT (PERSON_ID, BOOK_TITLE1, BOOK1_DUE_DATE, BOOK_TITLE2, BOOK2_DUE_DATE) VALUES (102, 'The Count of Monte Cristo','2020-08-15','The Lord of the Rings','2020-08-17');
INSERT INTO BOOK_CHECKOUTS_REPORT (PERSON_ID, BOOK_TITLE1, BOOK1_DUE_DATE, BOOK_TITLE2, BOOK2_DUE_DATE) VALUES (103, 'Rich Dad Poor Dad','2020-07-19',null,null);
INSERT INTO BOOK_CHECKOUTS_REPORT (PERSON_ID, BOOK_TITLE1, BOOK1_DUE_DATE, BOOK_TITLE2, BOOK2_DUE_DATE) VALUES (104, 'The Intelligent Investor','2020-08-13',null,null);

SELECT *
FROM BOOK_CHECKOUTS_REPORT;


/*
DROP TABLE BOOK_CHECKOUTS_REPORT;
DROP TABLE LIBRARY_BOOKS;
DROP TABLE LIBRARY_CUSTOMERS;
*/



