USE test
GO

--new normalized table:
CREATE TABLE BOOK_CHECKOUTS
(
	PERSON_ID INT,
	ISBN CHAR(14),
	DUE_DATE DATE,
	CONSTRAINT BOOK_CHECKOUTS_CPK PRIMARY KEY (PERSON_ID, ISBN, DUE_DATE),
	CONSTRAINT BOOK_CHECKOUTS_ISBN_FK FOREIGN KEY (ISBN)
		REFERENCES LIBRARY_BOOKS (ISBN),
	CONSTRAINT BOOK_CHECKOUTS_PERSON_ID_FK FOREIGN KEY (PERSON_ID)
		REFERENCES LIBRARY_CUSTOMERS (PERSON_ID)
);


--original un-normalized table:
SELECT *
FROM BOOK_CHECKOUTS_REPORT; 

SELECT *
FROM LIBRARY_BOOKS;


--populate the new normalized table:
INSERT INTO BOOK_CHECKOUTS
SELECT 
S.PERSON_ID,
LB.ISBN,
S.DUE_DATE
FROM
	(
	SELECT
	PERSON_ID,
	BOOK_TITLE1 AS BOOK_TITLE,
	BOOK1_DUE_DATE AS DUE_DATE
	FROM BOOK_CHECKOUTS_REPORT
	WHERE BOOK_TITLE1 IS NOT NULL
	UNION
	SELECT 
	PERSON_ID,
	BOOK_TITLE2,
	BOOK2_DUE_DATE
	FROM BOOK_CHECKOUTS_REPORT
	WHERE BOOK_TITLE2 IS NOT NULL
	) S
JOIN LIBRARY_BOOKS LB
ON LB.BOOK_TITLE = S.BOOK_TITLE;


--select all rows from the new table:
SELECT *
FROM BOOK_CHECKOUTS;