USE test
GO

CREATE TABLE PROJECT_INFO 
(
PROJECT_ID INT,
PROJECT_NAME VARCHAR(30),
EMPLOYEE_ID INT,
EMPLOYEE_NAME VARCHAR(50),
DEPARTMENT_ID INT,
DEPARTMENT_NAME VARCHAR(30),
SALARY INT,
PROJECT_BUDGET INT
);

INSERT INTO PROJECT_INFO (PROJECT_ID, PROJECT_NAME, EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, SALARY, PROJECT_BUDGET) VALUES (101,'Digital Services',1,'B. Jones',1005,80000,25000);
INSERT INTO PROJECT_INFO (PROJECT_ID, PROJECT_NAME, EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, SALARY, PROJECT_BUDGET) VALUES (101,'Digital Services',2,'C. Snow',1004,90000,25000);
INSERT INTO PROJECT_INFO (PROJECT_ID, PROJECT_NAME, EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, SALARY, PROJECT_BUDGET) VALUES (102,'HR system',1,'B. Jones',1005,80000,30000);
INSERT INTO PROJECT_INFO (PROJECT_ID, PROJECT_NAME, EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, SALARY, PROJECT_BUDGET) VALUES (102,'HR system',3,'W. Glass',1004,100000,30000);
INSERT INTO PROJECT_INFO (PROJECT_ID, PROJECT_NAME, EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, SALARY, PROJECT_BUDGET) VALUES (102,'HR system',4,'S. Singh',1006,90000,30000);

SELECT *
FROM PROJECT_INFO;